# Generated by Django 4.2.30 on 2026-06-14 20:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('purchase_type', models.CharField(choices=[('Single', 'Single pieces'), ('Bale', 'Bulk bale')], default='Single', max_length=10)),
                ('total_pieces', models.PositiveIntegerField(help_text='Total pieces in the purchase (before removing unsellable)', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost in KES', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unsellable_pieces', models.PositiveIntegerField(default=0)),
                ('sellable_pieces', models.PositiveIntegerField(default=0)),
                ('cost_per_piece', models.DecimalField(decimal_places=2, default=0, help_text='Cost per sellable piece (KES)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='purchase_user_id_657f8d_idx'), models.Index(fields=['user', 'category'], name='purchase_user_id_f3f713_idx')],
            },
        ),
    ]
