# Generated by Django 4.2.30 on 2026-06-14 20:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='My Mitumba Shop', max_length=120)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wages', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Annual tax in KES. Divided by 12 for monthly share.', max_digits=12)),
                ('loan_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_months_paid', models.PositiveIntegerField(default=0)),
                ('unsellable_rate', models.PositiveSmallIntegerField(default=20, help_text='Percentage of pieces per bale that are damaged/unsellable', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Show low-stock warning when any category falls below this number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
                'db_table': 'shop_settings',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop_settings.shopsettings')),
            ],
            options={
                'db_table': 'shop_product_category',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('settings', 'name')},
            },
        ),
    ]
